[package]
name = "igdm-sentiment-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.15"
plotters = "0.3.6"
serde = "1.0.208"
serde_json = "1.0.125"
vader_sentiment = "0.1.1"
walkdir = "2.5.0"
